apiVersion: v1
kind: Service
metadata:
    name: "aks1-6015"
    labels:
        app: "aks1-6015"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "aks1-6015"