apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nhltop
  name: nhltop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nhltop
  template:
    metadata:
      labels:
        app: nhltop
    spec:
      containers:
      - env:
        - name: DB_USER
          value: nhltop
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appsec
              key: db_password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: appconf
              key: db_name
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: appconf
              key: db_host
        image: to_be_overrided_by_kubectl_set_image
        imagePullPolicy: Always
        name: nhltop
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
