apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nhltop
  name: nhltop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nhltop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nhltop
    spec:
      containers:
      - env:
        - name: DB_USER
          value: nhltop
        - name: DB_PASSWORD
          value: {{ db_password }}
        - name: DB_NAME
          value: {{ db_name }}
        - name: DB_HOST
          value: {{ db_host }}
        image: {{ registry_address }}/nhltop:latest
        imagePullPolicy: Always
        name: nhltop
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
