apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nhltop
  name: nhltop
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nhltop
  template:
    metadata:
      labels:
        app: nhltop
    spec:
      containers:
      - env:
        - name: DB_USER
          value: nhltop
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appsec
              key: db_password
        - name: DB_NAME
          value: nhltop
        - name: DB_HOST
          value: mskepamdiplomadb.mariadb.database.azure.com
        image: mskepamdiplomaacr.azurecr.io/nhltop:1.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
        name: nhltop
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: msk-epam-diploma-prod
  labels:
    app: nhltop
  name: nhltop
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: nhltop
  sessionAffinity: None
  type: LoadBalancer
