apiVersion: v1
kind: Service
metadata:
  labels:
    app: nhltop
  name: nhltop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: nhltop
  sessionAffinity: None
  type: LoadBalancer
