on:
  push:
    paths:
      - app/**
    tags:
      - v[0-9].[0-9]+
env:
  ACR: mskepamdiplomaacr.azurecr.io
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Get version tag and branch
      run: |
        # Short name for current branch. For PRs, use target branch (base ref)
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
        GIT_TAG=${GITHUB_REF#refs/tags/}
        echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
        # Set k8s namespace name
        if [ $GIT_BRANCH = 'main' ]
          then echo "NAMESPACE=prod" >> $GITHUB_ENV
          else echo "NAMESPACE=dev"  >> $GITHUB_ENV
        fi
        # Set docker image path
        echo "IMAGE=${{ env.ACR }}/nhltop:$GIT_TAG" >> $GITHUB_ENV

    - name: Checkout repository 
      uses: actions/checkout@v2
    
    - name: Login to container registry 
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push image
      run: |
        docker build "$GITHUB_WORKSPACE/app" \
               -f "app/Dockerfile" \
               -t ${{ env.IMAGE }} \
               --label dockerfile-path=app/Dockerfile
        docker push ${{ env.IMAGE }}
    
    - name: Set kubernetes context
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Set deployment image
      run: |
        kubectl -n ${{ env.NAMESPACE }} \
          set image deploy/nhltop *=${{ env.IMAGE }}

